# Generated by Django 5.1.1 on 2024-10-21 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0003_alter_question_quiz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='choices', to=settings.AUTH_USER_MODEL),
        ),
    ]
